server:
  port: 8081
eureka:
  client:
    service-url:
        defaultZone:  http://server7998:7998/eureka/,http://server7999:7999/eureka/
spring:
  application:
    name: service-consumer-feign
feign:
  hystrix:
    enabled: true

